---
title: "03-075"
author: "Alex Cookson"
date: "15/05/2020"
output: html_document
---

### Question 1

Refer back to the table of useful mutate and filtering functions. Describe how each operation change when you combine it with grouping.


### Question 2

Which plane (`tailnum`) has the worst on-time record?


### Question 3

What time of day should you fly if you want to avoid delays as much as possible?


### Question 4

For each destination, compute the total minutes of delay. For each flight, compute the proportion of the total delay for its destination.


### Question 5

Delays are typically temporally correlated: even once the problem that caused the initial delay has been resolved, later flights are delayed to allow earlier flights to leave. Using `lag()`, explore how the delay of a flight is related to the delay of the immediately preceding flight.


### Question 6

Look at teach destination. Can you find flights that are suspiciously fast? (That is, flights that represent a potential data entry error.) Compute the air time of a flight relative to the shortest flight to that destination. Which flights were most delayed in the air?


### Question 7

Find all destinations that are flown by at least two carriers. Use that information to rank the carriers.
