---
title: "10-191"
author: "Alex Cookson"
date: "16/05/2020"
output: html_document
---

### Question 1

What does it mean for a flight to have a missing `tailnum`? What do the tail numbers that don't have a matching record in `planes` have in common? (Hint: one variable explains ~90% of the problems.)


### Question 2

Filter flights to only show flights with planes that have flown at least 100 flights.


### Question 3

Combine `fueleconomy::vehicles` and `fueleconomy::common` to find only the records for the most common models.


### Question 4

Find the 48 hours (over the course of the whole year) that have the worst delays. Cross-reference it with the `weather` data. Can you see any patterns?


### Question 5

What does `anti_join(flights, airports, by = c("dest" = "faa"))` tell you? What does `anti_join(airports, flights, by = c("faa" = "dest"))` tell you?


### Question 6

You might expect that there's an implicit relationship between plane and airline, because each plane is flown by a single airline. Confirm or reject this hypothesis using the tools you've learned in the preceding section.
