---
title: "08-136"
author: "Alex Cookson"
date: "16/05/2020"
output: html_document
---

### Question 1

What are the most important arguments to `locale()`?


### Question 2

What happens if you try and set `decimal_mark` and `grouping_mark` to the same character? What happens to the default value of `grouping_mark` when you set `decimal_mark` to "`,`"? What happens to the default value of `decimal_mark` when you set the `grouping_mark` to `.`?


### Question 3

I didn't discuss the `date_format` and `time_format` options to `locale()`. What do they do? Construct an example that shows when they might be useful.


### Question 4

If you live outside the US, create a new locale object that encapsulates the settings for the types of files you read most commonly.


### Question 5

What's the difference between `read_csv()` and `read_csv2()`?


### Question 6

What are the most common encodings used in Europe? What are the most common encodings used in Asia? Do some googling to find out.


### Question 7

Generate the correct format string to parse each of the following dates and times:

```{r q7, eval = FALSE}
d1 <- "January 1, 2010"
d2 <- "2015-Mar-07"
d3 <- "06-Jun-2017"
d4 <- c("August 19 (2015)", "July 1 (2015)")
d5 <- "12/30/14" # Dec 30, 2014
t1 <- "1705"
t2 <- "11:15:10.12 PM"
```

