---
title: "21-426"
author: "Alex Cookson"
date: "18/05/2020"
output: html_document
---

### Question 1

Create a new notebook using *File > New File > R Notebook*. Read the instructions. Practice running the chunks. Verify that you can modify the code, rerun it, and see modified output.


### Question 2

Create a new R Markdown document with *File > New File > R Markdown...* Knit it by clicking the appropriate button. Knit it by using the appropriate keyboard shortcut. Verify that you can modify the input and see the output update.


### Question 3

Compare and contrast the R Notebook and R Markdown files you created earlier. How are the outputs similar? How are they different? How are the inputs similar? How are they different? What happens if you copy the YAML header from one to the other?


### Question 4

Create one new R Markdown document for each of the three built-in formats: HTML, PDF, and Word. Knit each of the three documents. How does the output differ? How does the input differ? (You may need to install LaTeX in order to build the PDF output -- RStudio will prompt you if this is necessary.)